### ISSUE TITLE
Heroku deployment fails

### ISSUE THREAD

**Issue by frollo** [inoda/journal#19]
I've tried to deploy Journal using the provided Heroku button, but it fails silently. After forking and redeploying it, I get this error `undefined method 'unpack1' for nil:NilClass` after running some of the migrations.

You can see the whole error log here:

```
D, [2020-07-23T14:23:48.285981 #20] DEBUG -- :    (15.1ms)  CREATE TABLE "schema_migrations" ("version" character varying NOT NULL PRIMARY KEY)
D, [2020-07-23T14:23:48.296904 #20] DEBUG -- :    (8.2ms)  CREATE TABLE "ar_internal_metadata" ("key" character varying NOT NULL PRIMARY KEY, "value" character varying, "created_at" timestamp(6) NOT NULL, "updated_at" timestamp(6) NOT NULL)
D, [2020-07-23T14:23:48.327941 #20] DEBUG -- :    (1.0ms)  SELECT pg_try_advisory_lock(3896631746945074410)
D, [2020-07-23T14:23:48.340743 #20] DEBUG -- :    (1.2ms)  SELECT "schema_migrations"."version" FROM "schema_migrations" ORDER BY "schema_migrations"."version" ASC
I, [2020-07-23T14:23:48.341781 #20]  INFO -- : Migrating to CreatePosts (20190608151826)
== 20190608151826 CreatePosts: migrating ======================================
-- create_table(:posts, {})
D, [2020-07-23T14:23:48.344985 #20] DEBUG -- :    (0.9ms)  BEGIN
D, [2020-07-23T14:23:48.353726 #20] DEBUG -- :    (8.6ms)  CREATE TABLE "posts" ("id" bigserial primary key, "title" bytea NOT NULL, "content" bytea NOT NULL, "title_iv" bytea NOT NULL, "content_iv" bytea NOT NULL, "created_at" timestamp NOT NULL, "updated_at" timestamp NOT NULL)
   -> 0.0102s
== 20190608151826 CreatePosts: migrated (0.0102s) =============================
D, [2020-07-23T14:23:48.361394 #20] DEBUG -- :   primary::SchemaMigration Create (1.1ms)  INSERT INTO "schema_migrations" ("version") VALUES ($1) RETURNING "version"  [["version", "20190608151826"]]
D, [2020-07-23T14:23:48.367978 #20] DEBUG -- :    (6.4ms)  COMMIT
I, [2020-07-23T14:23:48.368049 #20]  INFO -- : Migrating to CreateTags (20190608151934)
== 20190608151934 CreateTags: migrating =======================================
-- create_table(:tags, {})
D, [2020-07-23T14:23:48.369683 #20] DEBUG -- :    (0.9ms)  BEGIN
D, [2020-07-23T14:23:48.376802 #20] DEBUG -- :    (7.0ms)  CREATE TABLE "tags" ("id" bigserial primary key, "label" bytea NOT NULL, "label_iv" bytea NOT NULL, "created_at" timestamp NOT NULL, "updated_at" timestamp NOT NULL)
   -> 0.0084s
== 20190608151934 CreateTags: migrated (0.0085s) ==============================
D, [2020-07-23T14:23:48.378322 #20] DEBUG -- :   primary::SchemaMigration Create (1.0ms)  INSERT INTO "schema_migrations" ("version") VALUES ($1) RETURNING "version"  [["version", "20190608151934"]]
D, [2020-07-23T14:23:48.382514 #20] DEBUG -- :    (4.0ms)  COMMIT
I, [2020-07-23T14:23:48.382577 #20]  INFO -- : Migrating to CreatePostsTags (20190608152033)
== 20190608152033 CreatePostsTags: migrating ==================================
-- create_table(:post_tags, {})
D, [2020-07-23T14:23:48.384098 #20] DEBUG -- :    (0.9ms)  BEGIN
D, [2020-07-23T14:23:48.388836 #20] DEBUG -- :    (4.6ms)  CREATE TABLE "post_tags" ("id" bigserial primary key, "post_id" integer NOT NULL, "tag_id" integer NOT NULL, "created_at" timestamp NOT NULL, "updated_at" timestamp NOT NULL)
   -> 0.0060s
-- add_index(:post_tags, :post_id)
D, [2020-07-23T14:23:48.396972 #20] DEBUG -- :    (3.4ms)  CREATE  INDEX  "index_post_tags_on_post_id" ON "post_tags"  ("post_id")
   -> 0.0081s
-- add_index(:post_tags, :tag_id)
D, [2020-07-23T14:23:48.403344 #20] DEBUG -- :    (3.2ms)  CREATE  INDEX  "index_post_tags_on_tag_id" ON "post_tags"  ("tag_id")
   -> 0.0063s
== 20190608152033 CreatePostsTags: migrated (0.0205s) =========================
D, [2020-07-23T14:23:48.404918 #20] DEBUG -- :   primary::SchemaMigration Create (1.0ms)  INSERT INTO "schema_migrations" ("version") VALUES ($1) RETURNING "version"  [["version", "20190608152033"]]
D, [2020-07-23T14:23:48.409670 #20] DEBUG -- :    (4.6ms)  COMMIT
I, [2020-07-23T14:23:48.409736 #20]  INFO -- : Migrating to CreateUsers (20190609224748)
== 20190609224748 CreateUsers: migrating ======================================
-- create_table(:users, {})
D, [2020-07-23T14:23:48.411493 #20] DEBUG -- :    (0.9ms)  BEGIN
D, [2020-07-23T14:23:48.419036 #20] DEBUG -- :    (7.4ms)  CREATE TABLE "users" ("id" bigserial primary key, "username" character varying NOT NULL, "password" character varying NOT NULL, "created_at" timestamp NOT NULL, "updated_at" timestamp NOT NULL)
   -> 0.0089s
== 20190609224748 CreateUsers: migrated (0.0090s) =============================
D, [2020-07-23T14:23:48.420507 #20] DEBUG -- :   primary::SchemaMigration Create (0.9ms)  INSERT INTO "schema_migrations" ("version") VALUES ($1) RETURNING "version"  [["version", "20190609224748"]]
D, [2020-07-23T14:23:48.425567 #20] DEBUG -- :    (4.9ms)  COMMIT
I, [2020-07-23T14:23:48.425632 #20]  INFO -- : Migrating to AddShareTokenToPosts (20190622045354)
== 20190622045354 AddShareTokenToPosts: migrating =============================
-- add_column(:posts, :sharing_token, :string)
D, [2020-07-23T14:23:48.427104 #20] DEBUG -- :    (0.9ms)  BEGIN
D, [2020-07-23T14:23:48.428764 #20] DEBUG -- :    (1.6ms)  ALTER TABLE "posts" ADD "sharing_token" character varying
   -> 0.0028s
-- add_index(:posts, :sharing_token, {:unique=>true})
D, [2020-07-23T14:23:48.437632 #20] DEBUG -- :    (4.5ms)  CREATE UNIQUE INDEX  "index_posts_on_sharing_token" ON "posts"  ("sharing_token")
   -> 0.0088s
== 20190622045354 AddShareTokenToPosts: migrated (0.0117s) ====================
D, [2020-07-23T14:23:48.439130 #20] DEBUG -- :   primary::SchemaMigration Create (1.0ms)  INSERT INTO "schema_migrations" ("version") VALUES ($1) RETURNING "version"  [["version", "20190622045354"]]
D, [2020-07-23T14:23:48.446434 #20] DEBUG -- :    (7.1ms)  COMMIT
I, [2020-07-23T14:23:48.446502 #20]  INFO -- : Migrating to ReviseSharingData (20190624033659)
== 20190624033659 ReviseSharingData: migrating ================================
-- remove_column(:posts, :sharing_token)
D, [2020-07-23T14:23:48.447860 #20] DEBUG -- :    (0.9ms)  BEGIN
D, [2020-07-23T14:23:48.452410 #20] DEBUG -- :    (4.4ms)  ALTER TABLE "posts" DROP COLUMN "sharing_token"
   -> 0.0056s
-- add_column(:posts, :sharing_token, :binary)
D, [2020-07-23T14:23:48.453805 #20] DEBUG -- :    (1.1ms)  ALTER TABLE "posts" ADD "sharing_token" bytea
   -> 0.0014s
-- add_column(:posts, :sharing_token_iv, :binary)
D, [2020-07-23T14:23:48.455434 #20] DEBUG -- :    (1.4ms)  ALTER TABLE "posts" ADD "sharing_token_iv" bytea
   -> 0.0016s
-- add_column(:posts, :listed_publicly, :boolean, {:null=>false, :default=>false})
D, [2020-07-23T14:23:48.458915 #20] DEBUG -- :    (2.2ms)  ALTER TABLE "posts" ADD "listed_publicly" boolean DEFAULT FALSE NOT NULL
   -> 0.0034s
-- add_index(:posts, :sharing_token, {:unique=>true})
D, [2020-07-23T14:23:48.465780 #20] DEBUG -- :    (3.8ms)  CREATE UNIQUE INDEX  "index_posts_on_sharing_token" ON "posts"  ("sharing_token")
   -> 0.0068s
-- add_index(:posts, :listed_publicly)
D, [2020-07-23T14:23:48.472180 #20] DEBUG -- :    (3.3ms)  CREATE  INDEX  "index_posts_on_listed_publicly" ON "posts"  ("listed_publicly")
   -> 0.0064s
== 20190624033659 ReviseSharingData: migrated (0.0254s) =======================
D, [2020-07-23T14:23:48.473629 #20] DEBUG -- :   primary::SchemaMigration Create (0.9ms)  INSERT INTO "schema_migrations" ("version") VALUES ($1) RETURNING "version"  [["version", "20190624033659"]]
D, [2020-07-23T14:23:48.480112 #20] DEBUG -- :    (6.3ms)  COMMIT
I, [2020-07-23T14:23:48.480178 #20]  INFO -- : Migrating to CreatePrompts (20190704052742)
rake aborted!
StandardError: An error has occurred, this and all later migrations canceled:
undefined method `unpack1' for nil:NilClass
/app/app/lib/encryptor.rb:8:in `encrypt'
/app/app/models/prompt.rb:9:in `content='
/app/vendor/bundle/ruby/2.6.0/gems/activemodel-6.0.3.2/lib/active_model/attribute_assignment.rb:50:in `public_send'
/app/vendor/bundle/ruby/2.6.0/gems/activemodel-6.0.3.2/lib/active_model/attribute_assignment.rb:50:in `_assign_attribute'
/app/vendor/bundle/ruby/2.6.0/gems/activemodel-6.0.3.2/lib/active_model/attribute_assignment.rb:43:in `block in _assign_attributes'
/app/vendor/bundle/ruby/2.6.0/gems/activemodel-6.0.3.2/lib/active_model/attribute_assignment.rb:42:in `each'
/app/vendor/bundle/ruby/2.6.0/gems/activemodel-6.0.3.2/lib/active_model/attribute_assignment.rb:42:in `_assign_attributes'
/app/vendor/bundle/ruby/2.6.0/gems/activerecord-6.0.3.2/lib/active_record/attribute_assignment.rb:21:in `_assign_attributes'
/app/vendor/bundle/ruby/2.6.0/gems/activemodel-6.0.3.2/lib/active_model/attribute_assignment.rb:35:in `assign_attributes'
/app/vendor/bundle/ruby/2.6.0/gems/activerecord-6.0.3.2/lib/active_record/core.rb:325:in `initialize'
/app/vendor/bundle/ruby/2.6.0/gems/activerecord-6.0.3.2/lib/active_record/inheritance.rb:70:in `new'
/app/vendor/bundle/ruby/2.6.0/gems/activerecord-6.0.3.2/lib/active_record/inheritance.rb:70:in `new'
/app/vendor/bundle/ruby/2.6.0/gems/activerecord-6.0.3.2/lib/active_record/persistence.rb:37:in `create'
/app/db/migrate/20190704054248_seed_prompts.rb:3:in `change'
/app/vendor/bundle/ruby/2.6.0/gems/activerecord-6.0.3.2/lib/active_record/migration.rb:828:in `exec_migration'
/app/vendor/bundle/ruby/2.6.0/gems/activerecord-6.0.3.2/lib/active_record/migration.rb:812:in `block (2 levels) in migrate'
/app/vendor/bundle/ruby/2.6.0/gems/activerecord-6.0.3.2/lib/active_record/migration.rb:811:in `block in migrate'
/app/vendor/bundle/ruby/2.6.0/gems/activerecord-6.0.3.2/lib/active_record/connection_adapters/abstract/connection_pool.rb:471:in `with_connection'
/app/vendor/bundle/ruby/2.6.0/gems/activerecord-6.0.3.2/lib/active_record/migration.rb:810:in `migrate'
/app/vendor/bundle/ruby/2.6.0/gems/activerecord-6.0.3.2/lib/active_record/migration.rb:1002:in `migrate'
/app/vendor/bundle/ruby/2.6.0/gems/activerecord-6.0.3.2/lib/active_record/migration.rb:1310:in `block in execute_migration_in_transaction'
/app/vendor/bundle/ruby/2.6.0/gems/activerecord-6.0.3.2/lib/active_record/migration.rb:1361:in `block in ddl_transaction'
/app/vendor/bundle/ruby/2.6.0/gems/activerecord-6.0.3.2/lib/active_record/connection_adapters/abstract/database_statements.rb:280:in `block in transaction'
/app/vendor/bundle/ruby/2.6.0/gems/activerecord-6.0.3.2/lib/active_record/connection_adapters/abstract/transaction.rb:280:in `block in within_new_transaction'
/app/vendor/bundle/ruby/2.6.0/gems/activesupport-6.0.3.2/lib/active_support/concurrency/load_interlock_aware_monitor.rb:26:in `block (2 levels) in synchronize'
/app/vendor/bundle/ruby/2.6.0/gems/activesupport-6.0.3.2/lib/active_support/concurrency/load_interlock_aware_monitor.rb:25:in `handle_interrupt'
/app/vendor/bundle/ruby/2.6.0/gems/activesupport-6.0.3.2/lib/active_support/concurrency/load_interlock_aware_monitor.rb:25:in `block in synchronize'
/app/vendor/bundle/ruby/2.6.0/gems/activesupport-6.0.3.2/lib/active_support/concurrency/load_interlock_aware_monitor.rb:21:in `handle_interrupt'
/app/vendor/bundle/ruby/2.6.0/gems/activesupport-6.0.3.2/lib/active_support/concurrency/load_interlock_aware_monitor.rb:21:in `synchronize'
/app/vendor/bundle/ruby/2.6.0/gems/activerecord-6.0.3.2/lib/active_record/connection_adapters/abstract/transaction.rb:278:in `within_new_transaction'
/app/vendor/bundle/ruby/2.6.0/gems/activerecord-6.0.3.2/lib/active_record/connection_adapters/abstract/database_statements.rb:280:in `transaction'
/app/vendor/bundle/ruby/2.6.0/gems/activerecord-6.0.3.2/lib/active_record/transactions.rb:212:in `transaction'
/app/vendor/bundle/ruby/2.6.0/gems/activerecord-6.0.3.2/lib/active_record/migration.rb:1361:in `ddl_transaction'
/app/vendor/bundle/ruby/2.6.0/gems/activerecord-6.0.3.2/lib/active_record/migration.rb:1309:in `execute_migration_in_transaction'
/app/vendor/bundle/ruby/2.6.0/gems/activerecord-6.0.3.2/lib/active_record/migration.rb:1281:in `block in migrate_without_lock'
/app/vendor/bundle/ruby/2.6.0/gems/activerecord-6.0.3.2/lib/active_record/migration.rb:1280:in `each'
/app/vendor/bundle/ruby/2.6.0/gems/activerecord-6.0.3.2/lib/active_record/migration.rb:1280:in `migrate_without_lock'
/app/vendor/bundle/ruby/2.6.0/gems/activerecord-6.0.3.2/lib/active_record/migration.rb:1229:in `block in migrate'
/app/vendor/bundle/ruby/2.6.0/gems/activerecord-6.0.3.2/lib/active_record/migration.rb:1382:in `with_advisory_lock'
/app/vendor/bundle/ruby/2.6.0/gems/activerecord-6.0.3.2/lib/active_record/migration.rb:1229:in `migrate'
/app/vendor/bundle/ruby/2.6.0/gems/activerecord-6.0.3.2/lib/active_record/migration.rb:1061:in `up'
/app/vendor/bundle/ruby/2.6.0/gems/activerecord-6.0.3.2/lib/active_record/migration.rb:1036:in `migrate'
/app/vendor/bundle/ruby/2.6.0/gems/activerecord-6.0.3.2/lib/active_record/tasks/database_tasks.rb:238:in `migrate'
/app/vendor/bundle/ruby/2.6.0/gems/activerecord-6.0.3.2/lib/active_record/railties/databases.rake:86:in `block (3 levels) in <top (required)>'
/app/vendor/bundle/ruby/2.6.0/gems/activerecord-6.0.3.2/lib/active_record/railties/databases.rake:84:in `each'
/app/vendor/bundle/ruby/2.6.0/gems/activerecord-6.0.3.2/lib/active_record/railties/databases.rake:84:in `block (2 levels) in <top (required)>'
/app/vendor/bundle/ruby/2.6.0/gems/rake-13.0.1/exe/rake:27:in `<top (required)>'
/app/vendor/bundle/ruby/2.6.0/gems/bundler-2.0.2/lib/bundler/cli/exec.rb:74:in `load'
/app/vendor/bundle/ruby/2.6.0/gems/bundler-2.0.2/lib/bundler/cli/exec.rb:74:in `kernel_load'
/app/vendor/bundle/ruby/2.6.0/gems/bundler-2.0.2/lib/bundler/cli/exec.rb:28:in `run'
/app/vendor/bundle/ruby/2.6.0/gems/bundler-2.0.2/lib/bundler/cli.rb:465:in `exec'
/app/vendor/bundle/ruby/2.6.0/gems/bundler-2.0.2/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
/app/vendor/bundle/ruby/2.6.0/gems/bundler-2.0.2/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
/app/vendor/bundle/ruby/2.6.0/gems/bundler-2.0.2/lib/bundler/vendor/thor/lib/thor.rb:387:in `dispatch'
/app/vendor/bundle/ruby/2.6.0/gems/bundler-2.0.2/lib/bundler/cli.rb:27:in `dispatch'
/app/vendor/bundle/ruby/2.6.0/gems/bundler-2.0.2/lib/bundler/vendor/thor/lib/thor/base.rb:466:in `start'
/app/vendor/bundle/ruby/2.6.0/gems/bundler-2.0.2/lib/bundler/cli.rb:18:in `start'
/app/vendor/bundle/ruby/2.6.0/gems/bundler-2.0.2/exe/bundle:30:in `block in <top (required)>'
/app/vendor/bundle/ruby/2.6.0/gems/bundler-2.0.2/lib/bundler/friendly_errors.rb:124:in `with_friendly_errors'
/app/vendor/bundle/ruby/2.6.0/gems/bundler-2.0.2/exe/bundle:22:in `<top (required)>'
/app/bin/bundle:3:in `load'
/app/bin/bundle:3:in `<main>'
Caused by:
NoMethodError: undefined method `unpack1' for nil:NilClass
/app/app/lib/encryptor.rb:8:in `encrypt'
/app/app/models/prompt.rb:9:in `content='
/app/vendor/bundle/ruby/2.6.0/gems/activemodel-6.0.3.2/lib/active_model/attribute_assignment.rb:50:in `public_send'
/app/vendor/bundle/ruby/2.6.0/gems/activemodel-6.0.3.2/lib/active_model/attribute_assignment.rb:50:in `_assign_attribute'
/app/vendor/bundle/ruby/2.6.0/gems/activemodel-6.0.3.2/lib/active_model/attribute_assignment.rb:43:in `block in _assign_attributes'
/app/vendor/bundle/ruby/2.6.0/gems/activemodel-6.0.3.2/lib/active_model/attribute_assignment.rb:42:in `each'
/app/vendor/bundle/ruby/2.6.0/gems/activemodel-6.0.3.2/lib/active_model/attribute_assignment.rb:42:in `_assign_attributes'
/app/vendor/bundle/ruby/2.6.0/gems/activerecord-6.0.3.2/lib/active_record/attribute_assignment.rb:21:in `_assign_attributes'
/app/vendor/bundle/ruby/2.6.0/gems/activemodel-6.0.3.2/lib/active_model/attribute_assignment.rb:35:in `assign_attributes'
/app/vendor/bundle/ruby/2.6.0/gems/activerecord-6.0.3.2/lib/active_record/core.rb:325:in `initialize'
/app/vendor/bundle/ruby/2.6.0/gems/activerecord-6.0.3.2/lib/active_record/inheritance.rb:70:in `new'
/app/vendor/bundle/ruby/2.6.0/gems/activerecord-6.0.3.2/lib/active_record/inheritance.rb:70:in `new'
/app/vendor/bundle/ruby/2.6.0/gems/activerecord-6.0.3.2/lib/active_record/persistence.rb:37:in `create'
/app/db/migrate/20190704054248_seed_prompts.rb:3:in `change'
/app/vendor/bundle/ruby/2.6.0/gems/activerecord-6.0.3.2/lib/active_record/migration.rb:828:in `exec_migration'
/app/vendor/bundle/ruby/2.6.0/gems/activerecord-6.0.3.2/lib/active_record/migration.rb:812:in `block (2 levels) in migrate'
/app/vendor/bundle/ruby/2.6.0/gems/activerecord-6.0.3.2/lib/active_record/migration.rb:811:in `block in migrate'
/app/vendor/bundle/ruby/2.6.0/gems/activerecord-6.0.3.2/lib/active_record/connection_adapters/abstract/connection_pool.rb:471:in `with_connection'
/app/vendor/bundle/ruby/2.6.0/gems/activerecord-6.0.3.2/lib/active_record/migration.rb:810:in `migrate'
/app/vendor/bundle/ruby/2.6.0/gems/activerecord-6.0.3.2/lib/active_record/migration.rb:1002:in `migrate'
/app/vendor/bundle/ruby/2.6.0/gems/activerecord-6.0.3.2/lib/active_record/migration.rb:1310:in `block in execute_migration_in_transaction'
/app/vendor/bundle/ruby/2.6.0/gems/activerecord-6.0.3.2/lib/active_record/migration.rb:1361:in `block in ddl_transaction'
/app/vendor/bundle/ruby/2.6.0/gems/activerecord-6.0.3.2/lib/active_record/connection_adapters/abstract/database_statements.rb:280:in `block in transaction'
/app/vendor/bundle/ruby/2.6.0/gems/activerecord-6.0.3.2/lib/active_record/connection_adapters/abstract/transaction.rb:280:in `block in within_new_transaction'
/app/vendor/bundle/ruby/2.6.0/gems/activesupport-6.0.3.2/lib/active_support/concurrency/load_interlock_aware_monitor.rb:26:in `block (2 levels) in synchronize'
/app/vendor/bundle/ruby/2.6.0/gems/activesupport-6.0.3.2/lib/active_support/concurrency/load_interlock_aware_monitor.rb:25:in `handle_interrupt'
/app/vendor/bundle/ruby/2.6.0/gems/activesupport-6.0.3.2/lib/active_support/concurrency/load_interlock_aware_monitor.rb:25:in `block in synchronize'
/app/vendor/bundle/ruby/2.6.0/gems/activesupport-6.0.3.2/lib/active_support/concurrency/load_interlock_aware_monitor.rb:21:in `handle_interrupt'
/app/vendor/bundle/ruby/2.6.0/gems/activesupport-6.0.3.2/lib/active_support/concurrency/load_interlock_aware_monitor.rb:21:in `synchronize'
/app/vendor/bundle/ruby/2.6.0/gems/activerecord-6.0.3.2/lib/active_record/connection_adapters/abstract/transaction.rb:278:in `within_new_transaction'
/app/vendor/bundle/ruby/2.6.0/gems/activerecord-6.0.3.2/lib/active_record/connection_adapters/abstract/database_statements.rb:280:in `transaction'
/app/vendor/bundle/ruby/2.6.0/gems/activerecord-6.0.3.2/lib/active_record/transactions.rb:212:in `transaction'
/app/vendor/bundle/ruby/2.6.0/gems/activerecord-6.0.3.2/lib/active_record/migration.rb:1361:in `ddl_transaction'
/app/vendor/bundle/ruby/2.6.0/gems/activerecord-6.0.3.2/lib/active_record/migration.rb:1309:in `execute_migration_in_transaction'
/app/vendor/bundle/ruby/2.6.0/gems/activerecord-6.0.3.2/lib/active_record/migration.rb:1281:in `block in migrate_without_lock'
/app/vendor/bundle/ruby/2.6.0/gems/activerecord-6.0.3.2/lib/active_record/migration.rb:1280:in `each'
/app/vendor/bundle/ruby/2.6.0/gems/activerecord-6.0.3.2/lib/active_record/migration.rb:1280:in `migrate_without_lock'
/app/vendor/bundle/ruby/2.6.0/gems/activerecord-6.0.3.2/lib/active_record/migration.rb:1229:in `block in migrate'
/app/vendor/bundle/ruby/2.6.0/gems/activerecord-6.0.3.2/lib/active_record/migration.rb:1382:in `with_advisory_lock'
/app/vendor/bundle/ruby/2.6.0/gems/activerecord-6.0.3.2/lib/active_record/migration.rb:1229:in `migrate'
/app/vendor/bundle/ruby/2.6.0/gems/activerecord-6.0.3.2/lib/active_record/migration.rb:1061:in `up'
/app/vendor/bundle/ruby/2.6.0/gems/activerecord-6.0.3.2/lib/active_record/migration.rb:1036:in `migrate'
/app/vendor/bundle/ruby/2.6.0/gems/activerecord-6.0.3.2/lib/active_record/tasks/database_tasks.rb:238:in `migrate'
/app/vendor/bundle/ruby/2.6.0/gems/activerecord-6.0.3.2/lib/active_record/railties/databases.rake:86:in `block (3 levels) in <top (required)>'
/app/vendor/bundle/ruby/2.6.0/gems/activerecord-6.0.3.2/lib/active_record/railties/databases.rake:84:in `each'
/app/vendor/bundle/ruby/2.6.0/gems/activerecord-6.0.3.2/lib/active_record/railties/databases.rake:84:in `block (2 levels) in <top (required)>'
/app/vendor/bundle/ruby/2.6.0/gems/rake-13.0.1/exe/rake:27:in `<top (required)>'
/app/vendor/bundle/ruby/2.6.0/gems/bundler-2.0.2/lib/bundler/cli/exec.rb:74:in `load'
/app/vendor/bundle/ruby/2.6.0/gems/bundler-2.0.2/lib/bundler/cli/exec.rb:74:in `kernel_load'
/app/vendor/bundle/ruby/2.6.0/gems/bundler-2.0.2/lib/bundler/cli/exec.rb:28:in `run'
/app/vendor/bundle/ruby/2.6.0/gems/bundler-2.0.2/lib/bundler/cli.rb:465:in `exec'
/app/vendor/bundle/ruby/2.6.0/gems/bundler-2.0.2/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
/app/vendor/bundle/ruby/2.6.0/gems/bundler-2.0.2/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
/app/vendor/bundle/ruby/2.6.0/gems/bundler-2.0.2/lib/bundler/vendor/thor/lib/thor.rb:387:in `dispatch'
/app/vendor/bundle/ruby/2.6.0/gems/bundler-2.0.2/lib/bundler/cli.rb:27:in `dispatch'
/app/vendor/bundle/ruby/2.6.0/gems/bundler-2.0.2/lib/bundler/vendor/thor/lib/thor/base.rb:466:in `start'
/app/vendor/bundle/ruby/2.6.0/gems/bundler-2.0.2/lib/bundler/cli.rb:18:in `start'
/app/vendor/bundle/ruby/2.6.0/gems/bundler-2.0.2/exe/bundle:30:in `block in <top (required)>'
/app/vendor/bundle/ruby/2.6.0/gems/bundler-2.0.2/lib/bundler/friendly_errors.rb:124:in `with_friendly_errors'
/app/vendor/bundle/ruby/2.6.0/gems/bundler-2.0.2/exe/bundle:22:in `<top (required)>'
/app/bin/bundle:3:in `load'
/app/bin/bundle:3:in `<main>'
Tasks: TOP => db:migrate
(See full trace by running task with --trace)
== 20190704052742 CreatePrompts: migrating ====================================
-- create_table(:prompts, {})
D, [2020-07-23T14:23:48.481873 #20] DEBUG -- :    (0.8ms)  BEGIN
D, [2020-07-23T14:23:48.490260 #20] DEBUG -- :    (8.2ms)  CREATE TABLE "prompts" ("id" bigserial primary key, "content" bytea NOT NULL, "content_iv" bytea NOT NULL, "created_at" timestamp NOT NULL, "updated_at" timestamp NOT NULL)
   -> 0.0097s
== 20190704052742 CreatePrompts: migrated (0.0097s) ===========================
D, [2020-07-23T14:23:48.491824 #20] DEBUG -- :   primary::SchemaMigration Create (1.0ms)  INSERT INTO "schema_migrations" ("version") VALUES ($1) RETURNING "version"  [["version", "20190704052742"]]
D, [2020-07-23T14:23:48.494257 #20] DEBUG -- :    (2.2ms)  COMMIT
I, [2020-07-23T14:23:48.494321 #20]  INFO -- : Migrating to SeedPrompts (20190704054248)
== 20190704054248 SeedPrompts: migrating ======================================
D, [2020-07-23T14:23:48.498532 #20] DEBUG -- :    (0.9ms)  BEGIN
D, [2020-07-23T14:23:48.513918 #20] DEBUG -- :    (0.9ms)  ROLLBACK
D, [2020-07-23T14:23:48.516092 #20] DEBUG -- :    (1.1ms)  SELECT pg_advisory_unlock(3896631746945074410)
```

**Comment by inoda** [comment]
@frollo make sure you set up the ENV vars correctly:

CIPHER_KEY: Secret key used in encrypting. It needs to be 32 bytes base 64 encoded. Generate with Base64.encode64(SecureRandom.random_bytes(32)).

SHARING_TOKEN_CIPHER_IV: This is to make sure sharing token IVs are the same so we can find posts from a public route parameter. It needs to be 16 bytes base 64 encoded. Generate with Base64.encode64(SecureRandom.random_bytes(16)).
